# Version scratch
FROM scratch

# Définir le nom et le tag de l'image
LABEL tag="scratch"

# Copier le fichier hello.exe dans le conteneur
COPY hello.exe /app/hello.exe

# Exécuter hello.exe lorsque le conteneur est lancé
CMD ["/app/hello.exe"]
