# Version d'Ubuntu 22.04
FROM ubuntu:22.04

# Définir le nom et le tag de l'image
LABEL tag="ubuntu-22.04"

# Copier le fichier hello.exe dans le conteneur
COPY hello.exe /app/hello.exe

# Exécuter hello.exe lorsque le conteneur est lancé
CMD ["/app/hello.exe"]
